import "./globals.css";

import dynamic from "next/dynamic";
const Navbar = dynamic(() => import('@/components/navigation/navbar'))
const Footer = dynamic(() => import('@/components/navigation/footer'))

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className="flex flex-col min-h-screen _monica-theme-d2f2b383">
        <Navbar />
        <main className="flex-grow">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}